version: "3.7"
services: 
 postgres:
  build: 
    context: ./DB
    dockerfile: Dockerfile
  # image: postgres
  environment: 
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: password
  ports: 
   - '5432:5432'
  
  volumes: 
   - ./var/pgdata:/var/lib/postgresql/data

 node-postgre:
  build: 
   context: .
  environment: 
   DB_SCHEMA: api
   DB_USER: me
   DB_PASSWORD: password
   DB_HOST: postgres
  depends_on: 
   - postgres
  ports: 
   - '3000:3000'
  
volumes: 
 node-postgre-db: